---
###############################################################################
# Config
###############################################################################
# Steam user login is ONLY required for download, not running service.
#
# Reference:
# * https://satisfactory.wiki.gg/wiki/Dedicated_servers#Linux
# * http://developer.valvesoftware.com/wiki/Command_line_options

- name: '{{ "Config | filesystem | set " ~ left_4_dead_2__cfg._motd_file }}'
  ansible.builtin.copy:
    dest: '{{ left_4_dead_2__cfg._motd_file }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0644'
    content: '{{ left_4_dead_2__cfg._motd }}'

- name: '{{ "Config | filesystem | set " ~ left_4_dead_2__cfg._host_file }}'
  ansible.builtin.copy:
    dest: '{{ left_4_dead_2__cfg._host_file }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0644'
    content: '{{ left_4_dead_2__cfg._host }}'

- name: '{{ "Config | filesystem | set " ~ left_4_dead_2__cfg._server_file }}'
  ansible.builtin.template:
    src: 'server.cfg.j2'
    dest: '{{ left_4_dead_2__cfg._server_file }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0644'
  vars:
    server: '{{ left_4_dead_2__cfg._server }}'

- name: '{{ "Config | filesystem | set " ~ left_4_dead_2__cfg._admins_file }}'
  when: left_4_dead_2_flg_sourcemod
  ansible.builtin.template:
    src: 'admins_simple.ini.j2'
    dest: '{{ left_4_dead_2__cfg._admins_file }}'
    owner: '{{ steam__ctx._user }}'
    group: '{{ steam__ctx._group }}'
    mode: '0600'
