---
###############################################################################
# Install
###############################################################################

- name: 'Install | steamcmd'
  ansible.builtin.import_role:
    name: 'r_pufky.game.steam'
  vars:
    steam_flg_update: false
    steam_flg_metamod: '{{ left_4_dead_2_flg_metamod }}'
    steam_flg_sourcemod: '{{ left_4_dead_2_flg_sourcemod }}'
    steam_cfg_mod_branch: '{{ left_4_dead_2__srv._mod_branch }}'
    steam_cfg_mm_build: '{{ left_4_dead_2__srv._mm_build }}'
    steam_cfg_sm_build: '{{ left_4_dead_2__srv._sm_build }}'

- name: 'Install | filesystem | find current installation'
  ansible.builtin.stat:
    path: '{{ left_4_dead_2__cfg._app }}'
  register: left_4_dead_2__installed

- name: 'Install | fact | set install state'
  ansible.builtin.set_fact:
    left_4_dead_2__cfg: "{{ left_4_dead_2__cfg | r_pufky.data.v3(

        _is_installed=left_4_dead_2__installed.stat.exists,
        _admins_file=(
          left_4_dead_2__cfg._root_dir ~ steam__ctx._sourcemod_dirs[0] ~
          '/configs/admins_simple.ini'
        ),
        _env_file=steam__ctx._home ~ '/.steam/.env',
      ) }}"

- name: '{{ "Install | filesystem | " ~ left_4_dead_2__cfg._root_dir }}'
  ansible.builtin.file:
    path: '{{ left_4_dead_2__cfg._root_dir }}'
    owner: '{{ steam__ctx._uid }}'
    group: '{{ steam__ctx._gid }}'
    mode: '0755'
    state: 'directory'

- name: 'Install | systemd | set left_4_dead_2.service'
  ansible.builtin.template:
    src: 'systemd/left_4_dead_2.service.j2'
    dest: '/etc/systemd/system/left_4_dead_2.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
