---
# yamllint disable rule:line-length
###############################################################################
# Default
###############################################################################
# Default values result in running Left 4 Dead 2 server.
#
# Tests:
# * Sourcemod is installed correctly.
# * Metamod is installed correctly.
# * motd.txt set.
# * host.txt set.
# * server.cfg set.
# * admins_simple.ini set.
# * Left 4 Dead 2 server is running.

dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'libvirt'
    type: 'libvirt'
provisioner:
  name: 'ansible'
  connection_options:
    ansible_ssh_user: 'vagrant'
    ansible_become: true
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
  inventory:
    group_vars:
      all:
        url_inject_enable: true
        left_4_dead_2_cfg_admins:
          - user: 76561198021925107
            priv: '99:z'  # Root privileges.
        left_4_dead_2_cfg_host: 'test server'
        left_4_dead_2_cfg_motd: 'test server'
platforms:
  - name: 'left-4-dead-2-default'
    box: 'debian/trixie64'
    memory: 4096
    cpus: 2
    interfaces:
      - network_name: 'private_network'
        auto_config: true
        type: 'dhcp'
    instance_raw_config_args:
      - 'vm.network "forwarded_port", guest: 27015, host: 27015, protocol: "udp"'
      - 'vm.network "forwarded_port", guest: 27015, host: 27015, protocol: "tcp"'
      - 'vm.network "forwarded_port", guest: 27016, host: 27016, protocol: "udp"'
      - 'vm.network "forwarded_port", guest: 27016, host: 27016, protocol: "tcp"'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
