---
- name: 'Prepare | steamcmd'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    # Cache binaries for steamcmd installation (See: steam/molecule/prepare).
    - name: 'Prepare | check steam role'
      ansible.builtin.stat:
        path: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") | dirname ~
            "/steam/vars/main.yml"
          }}'
      register: left_4_dead_2__cmd

    - name: 'Prepare | assert | steam role exists'
      ansible.builtin.assert:
        quiet: true
        that: left_4_dead_2__cmd.stat.exists
        fail_msg: |

          ✘ steam role (r_pufky.game.steam) must exist adjacent to this role.

          roles/left_4_dead_2
          roles/steam

    - name: 'Prepare | import steam role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") | dirname ~
            "/steam/vars/main.yml"
          }}'

    - name: 'Prepare | cache'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare cache'

    - name: '{{ "Prepare | cache | Metamod " ~ steam___mm._version }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'cache_url.yml'
      vars:
        test_name:
          '{{ "Prepare | cache | Metamod " ~ steam___mm._version }}'
        test_dest: '{{ steam___mm._package }}'
        test_url: '{{ steam___mm._url }}'
        test_mode: '0640'

    - name: '{{ "Prepare | cache | Sourcemod " ~ steam___sm._version }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'cache_url.yml'
      vars:
        test_name:
          '{{ "Prepare | cache | Sourcemod " ~ steam___sm._version }}'
        test_dest: '{{ steam___sm._package }}'
        test_url: '{{ steam___sm._url }}'
        test_mode: '0640'

- name: 'Prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    # Cache binaries for steamcmd installation (See: steam/molecule/prepare).
    - name: 'Prepare | import steam role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") | dirname ~
            "/steam/vars/main.yml"
          }}'

    - name: 'Prepare | inject | cached packages'
      when: (url_inject_enable | default(false))
      ansible.builtin.copy:
        src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/molecule/cache/" ~
            item
          }}'
        dest: '{{ "/tmp/" ~ item }}'
        owner: 'root'
        group: 'root'
        mode: '0644'
      loop:
        - '{{ steam___mm._package }}'
        - '{{ steam___sm._package }}'
