---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Prepare | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: '{{ "Verify | test | " ~ left_4_dead_2___app._app_d }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name: '{{ "Verify | test | " ~ left_4_dead_2___app._app_d }}'
        test_src: '{{ "files/" ~ item }}'
        test_file: '{{ left_4_dead_2___app._app_d ~ "/" ~ item }}'
        test_owner: 'steam'
        test_group: 'steam'
        test_mode: '0644'
        test_diff: true
      loop:
        - 'motd.txt'
        - 'host.txt'

    - name: '{{ "Verify | test | " ~ left_4_dead_2___app._cfg_d }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name: '{{ "Verify | test | " ~ left_4_dead_2___app._cfg_d }}'
        test_src: 'files/server.cfg'
        test_file: '{{ left_4_dead_2___app._cfg_d ~ "/server.cfg" }}'
        test_owner: 'steam'
        test_group: 'steam'
        test_mode: '0644'
        test_diff: true

    - name: '{{ "Verify | test | " ~ left_4_dead_2___app._admin_ini }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name: '{{ "Verify | test | " ~ left_4_dead_2___app._admin_ini }}'
        test_src: 'files/admins_simple.ini'
        test_file: '{{ left_4_dead_2___app._admin_ini }}'
        test_owner: 'steam'
        test_group: 'steam'
        test_mode: '0600'
        test_diff: true
